---
info:
  title: Sonar
  description: Project Sonar
  x-cortex-git:
    github:
      alias: r7org
      repository: rapid7/sonar
  x-cortex-tag: sonar
  x-cortex-type: service
  x-cortex-domain-parents:
  - tag: octo-and-labs
  x-cortex-groups:
  - exposure:internal-ship
openapi: 3.0.1
servers:
- url: "/"
